version: '3'
services:
  app:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "npm install && npm run dev"
    networks:
      - common_net
  
networks:
  common_net: {}